"""empty message

Revision ID: 018d1aac290a
Revises: 
Create Date: 2023-11-07 00:34:29.157478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018d1aac290a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('salt', sa.String(length=80), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'general', name='userrol'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='usergender'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
